-- MySQL Script generated by MySQL Workbench
-- Fri Nov 14 08:26:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `idLattes` VARCHAR(17) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Nacionalidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPessoa`),
  UNIQUE INDEX `idPessoa_UNIQUE` (`idPessoa` ASC) VISIBLE,
  UNIQUE INDEX `idLattes_UNIQUE` (`idLattes` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Academico` (
  `idAcademico` INT NOT NULL AUTO_INCREMENT,
  `idPessoa` INT NOT NULL,
  `Nivel` VARCHAR(45) NOT NULL,
  `AnoTitulacao` YEAR(4) NOT NULL,
  PRIMARY KEY (`idAcademico`, `idPessoa`),
  INDEX `fk_Academico_1_idx` (`idPessoa` ASC) VISIBLE,
  UNIQUE INDEX `idAcademico_UNIQUE` (`idAcademico` ASC) VISIBLE,
  UNIQUE INDEX `idPessoa_UNIQUE` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Academico_1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Docente` (
  `idDocente` INT NOT NULL AUTO_INCREMENT,
  `idAcademico` INT NOT NULL,
  `SIAPE` VARCHAR(45) NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  PRIMARY KEY (`idDocente`, `idAcademico`),
  UNIQUE INDEX `idAcademico_UNIQUE` (`idAcademico` ASC) VISIBLE,
  UNIQUE INDEX `SIAPE_UNIQUE` (`SIAPE` ASC) VISIBLE,
  UNIQUE INDEX `idDocente_UNIQUE` (`idDocente` ASC) VISIBLE,
  CONSTRAINT `fk_Docente_1`
    FOREIGN KEY (`idAcademico`)
    REFERENCES `mydb`.`Academico` (`idAcademico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coordenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coordenador` (
  `idCoordenador` INT NOT NULL AUTO_INCREMENT,
  `idDocente` INT NOT NULL,  -- CORRIGIDO: mudado de VARCHAR para INT
  PRIMARY KEY (`idCoordenador`, `idDocente`),
  UNIQUE INDEX `idCoordenador_UNIQUE` (`idCoordenador` ASC) VISIBLE,
  UNIQUE INDEX `idDocente_UNIQUE` (`idDocente` ASC) VISIBLE,
  CONSTRAINT `fk_Coordenador_1`
    FOREIGN KEY (`idDocente`)
    REFERENCES `mydb`.`Docente` (`idDocente`)  -- CORRIGIDO: referenciando idDocente
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `idCoordenador` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLogin`, `idCoordenador`),
  UNIQUE INDEX `idLogin_UNIQUE` (`idLogin` ASC) VISIBLE,
  UNIQUE INDEX `idCoordenador_UNIQUE` (`idCoordenador` ASC) VISIBLE,
  CONSTRAINT `fk_Login_1`
    FOREIGN KEY (`idCoordenador`)
    REFERENCES `mydb`.`Coordenador` (`idCoordenador`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curriculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curriculo` (
  `idCurriculo` INT NOT NULL AUTO_INCREMENT,
  `idPessoa` INT NOT NULL,
  `UltimaAtualizacao` DATE NOT NULL,
  PRIMARY KEY (`idCurriculo`, `idPessoa`),
  UNIQUE INDEX `idCurriculo_UNIQUE` (`idCurriculo` ASC) VISIBLE,
  UNIQUE INDEX `idPessoa_UNIQUE` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Curriculo_1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoDeProducao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoDeProducao` (
  `idTipoDeProducao` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`idTipoDeProducao`),
  UNIQUE INDEX `idTipoDeProducao_UNIQUE` (`idTipoDeProducao` ASC) VISIBLE,
  UNIQUE INDEX `Tipo_UNIQUE` (`Tipo` ASC) VISIBLE,
  UNIQUE INDEX `Descricao_UNIQUE` (`Descricao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producao` (
  `idProducao` INT NOT NULL AUTO_INCREMENT,
  `idTipo` INT NOT NULL,
  `Autor` VARCHAR(45) NOT NULL,
  `Titulo` VARCHAR(512) NOT NULL,
  `DataDePublicacao` YEAR(4) NOT NULL,
  `Hash` VARCHAR(1) NULL,
  PRIMARY KEY (`idProducao`, `idTipo`),
  UNIQUE INDEX `idProducao_UNIQUE` (`idProducao` ASC) VISIBLE,
  INDEX `fk_Producao_2_idx` (`idTipo` ASC) VISIBLE,
  CONSTRAINT `fk_Producao_2`
    FOREIGN KEY (`idTipo`)
    REFERENCES `mydb`.`TipoDeProducao` (`idTipoDeProducao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CurriculoProducao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CurriculoProducao` (
  `idCurriculoProducao` INT NOT NULL AUTO_INCREMENT,
  `idCurriculo` INT NOT NULL,
  `idProducao` INT NOT NULL,
  PRIMARY KEY (`idCurriculoProducao`, `idCurriculo`, `idProducao`),
  UNIQUE INDEX `idCurriculoProducao_UNIQUE` (`idCurriculoProducao` ASC) VISIBLE,
  INDEX `fk_CurriculoProducao_1_idx` (`idCurriculo` ASC) VISIBLE,
  INDEX `fk_CurriculoProducao_2_idx` (`idProducao` ASC) VISIBLE,
  CONSTRAINT `fk_CurriculoProducao_1`
    FOREIGN KEY (`idCurriculo`)
    REFERENCES `mydb`.`Curriculo` (`idCurriculo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_CurriculoProducao_2`
    FOREIGN KEY (`idProducao`)
    REFERENCES `mydb`.`Producao` (`idProducao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coautores`
-- ---------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coautor` (
  `idCoautor` INT NOT NULL AUTO_INCREMENT,
  `idProducao` INT NOT NULL,
  `idAbreviatura` INT NOT NULL,
  PRIMARY KEY (`idCoautor`, `idProducao`, `idAbreviatura`),
  UNIQUE INDEX `idCoautor_UNIQUE` (`idCoautor` ASC) VISIBLE,
  INDEX `fk_Coautores_1_idx` (`idProducao` ASC) VISIBLE,
  INDEX `fk_Coautores_Pessoa1_idx` (`idAbreviatura` ASC) VISIBLE,
  CONSTRAINT `fk_Coautores_1`
    FOREIGN KEY (`idProducao`)
    REFERENCES `mydb`.`Producao` (`idProducao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Coautores_Pessoa1`
    FOREIGN KEY (`idAbreviatura`)
    REFERENCES `mydb`.`Abreviatura` (`idAbreviatura`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Abreviatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Abreviatura` (
  `idAbreviatura` INT NOT NULL AUTO_INCREMENT,
  `idPessoa` INT NULL,
  `Abreviatura` VARCHAR(45),
  PRIMARY KEY (`idAbreviatura`),
  UNIQUE INDEX `idAbreviatura_UNIQUE` (`idAbreviatura` ASC) VISIBLE,
  INDEX `fk_Abreviatura_1_idx` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Abreviatura_1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS
